services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    container_name: online_clearance_prod
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Environment variables will be loaded from .env file
    volumes:
      # Mount any persistent data if needed
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
