services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: online_clearance_dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app # 👈 Mount your local source into the container
      - /app/node_modules # 👈 Prevent overwriting node_modules
    restart: unless-stopped
    command: >
      sh -c "npx prisma generate &&
             npx nodemon --watch . --ext ts,json --exec 'npx ts-node src/index.ts'"
