name: Backend CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 3️⃣ Cache dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: |
            ascs-server-prisma/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-ascs-${{ hashFiles('ascs-server-prisma/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-ascs-

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: |
          cd ascs-server-prisma
          npm ci

      # 5️⃣ Build TypeScript
      - name: Build backend
        run: |
          cd ascs-server-prisma
          npm run build

      # 6️⃣ Run tests (optional)
      - name: Run tests
        run: |
          cd ascs-server-prisma
          npm test
