name: React Vite CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: 🧭 Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🧪 Run Tests
        run: |
          echo "No tests configured — skipping"
          # Uncomment below when you have test setup
          # npm test

      - name: 🏗️ Build Vite Project
        run: npm run build

      - name: 📂 Upload Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 🧭 Checkout Code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: 📥 Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-dist
          path: dist

      - name: 🚀 Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          vercel-args: "--prod"
